import Head from 'next/head'
import { VFC } from 'react'

export const SiteLayoutHead: VFC = () => {
  return (
    <Head>
      <title>PROM</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
  )
}
