name: Check PR project validity

on:
  pull_request:
    branches: ['main']

jobs:
  check-build:
    name: Check project build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - uses: n1hility/cancel-previous-runs@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: check-pr.yml

        # https://github.com/actions/checkout
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/cache@v4
        name: Cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Run prettier
        run: pnpm prettier

      - name: Run tests
        run: pnpm test

      - name: Build
        run: pnpm build:packages
