name: Check PR project validity

on:
  pull_request:
    branches: [ "main" ]

jobs:
  validate-pr-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-build:
    name: Check project build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: check-pr.yml

        # https://github.com/actions/checkout
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
            fetch-depth: 2

      - uses: actions/cache@v2
        name: Cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Run prettier
        run: yarn prettier

      - name: Run tests
        run: yarn test

      - name: Build
        run: yarn build:packages
