name: Check PR project validity

on:
  pull_request:
    branches: [ "main" ]

jobs:
  validate-pr-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-build:
    name: Check project build
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: check-pr.yml

      - name: Checkout Repo
        # https://github.com/actions/checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        name: Cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Run prettier
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: prettier

      - name: Run tests
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test

      - name: Build
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build:packages
