name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/**

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: version-and-release.yml

      - name: Checkout Repo
        # https://github.com/actions/checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        name: Cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn --frozen-lockfile

        # https://github.com/changesets/action
      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: yarn release
          version: yarn version-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}