name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - packages/**

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - uses: n1hility/cancel-previous-runs@v3
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: version-and-release.yml

      - name: Checkout Repo
        # https://github.com/actions/checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        name: Cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

        # https://github.com/changesets/action
      - name: Create Release Pull Request or Publish to node package registry
        uses: changesets/action@v1
        with:
          publish: pnpm run release
          version: pnpm run version-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Update lockfile after version
        run: pnpm i --frozen-lockfile=false

      - name: Create JSON schema and upload
        run: node scripts/generate-schema-and-upload.mjs
        env:
          PROM_FTP_CONNECTION_STRING: ${{ secrets.PROM_FTP_CONNECTION_STRING }}
       
          